AddonId: MAMEUtility_af854071-4cd2-47ae-a7b3-35c238f0f7c0_1_0_1
Packages:
  - Version: 1.0.1
    RequiredApiVersion: 6.0.0.0
    ReleaseDate: 2021-10-26
    PackageUrl: https://github.com/gerrykeys/playnite-mame-utility/releases/download/v1.0.1/MAMEUtility_af854071-4cd2-47ae-a7b3-35c238f0f7c0_1_0_1.pext
